name: Create Directory Workflow

on:
  push:
    branches:
      - main

jobs:
  create-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Check current time
        id: current_time
        run: echo "::set-output name=time::$(date +%s)"

      - name: Calculate next run time
        id: next_run_time
        run: echo "::set-output name=next_time::$(($(echo ${{ steps.current_time.outputs.time }})+180))"
        
      - name: Wait until next run time
        run: sleep $(( ${{ steps.next_run_time.outputs.next_time }} - $(date +%s) ))

      - name: Create Directory
        run: mkdir abc
