name: Run Schedule Script

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 2 minutes

jobs:
  run_schedule_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Update to use Node.js version 20

    - name: Execute Schedule.js
      run: |
        echo "Executing Schedule.js"
        node Schedule.js || exit 1
        echo "Schedule.js execution completed"
